# Generated by Django 5.1.4 on 2025-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_time',
            field=models.DateField(),
        ),
    ]
